# -*- coding: utf-8 -*-
"""data_analysis2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1giBLaL9buniPh-kCVKjHms_VI6WDhZXo
"""

import pandas as pd

import numpy as np

df=pd.read_csv("/content/diabetes.csv")

df

df.describe()

df.info

df.info()

df.isnull().sum()

df.replace(["?","N/A","NA",""],np.nan,inplace=True)

df

df["frame"]=df["frame"].fillna(df["frame"].mode()[0])

df.isnull().sum()

df=pd.read_csv("/content/diabetes.csv")

import pandas as pd

df=pd.read_csv("/content/diabetes.csv")

import pandas as pd

df=pd.read_csv("/content/diabetes.csv")

df

df.describe()

df.isnull().sum()

import numpy as np

df.replace(["?","N/A","NA",""],np.nan,inplace=True)

df

df["frame"]=df["frame"].fillna(df["frame"].mode()[0])

df.isnull().sum()